#!/usr/bin/env python3
"""
FurryOS Universal Patcher v8.1.0
One script to patch the entire project based on GENOME.yaml and USER_CONFIG.yaml
Author: AnthroHeart / Anthro Entertainment LLC
"""

import os
import sys
import yaml
import shutil
import stat
from pathlib import Path
from datetime import datetime

class FurryOSPatcher:
    def __init__(self):
        self.root = Path.cwd()
        self.config_dir = self.root / "config"
        self.assets_dir = self.root / "assets"
        self.scripts_dir = self.root / "scripts"

        # Load configuration
        self.genome = self.load_yaml("GENOME.yaml")
        self.user_config = self.load_yaml("USER_CONFIG.yaml")

        self.errors = []
        self.warnings = []
        self.fixes_applied = []

    def load_yaml(self, filename):
        """Load YAML configuration file"""
        yaml_path = self.config_dir / filename
        if not yaml_path.exists():
            # Try root directory
            yaml_path = self.root / filename

        if not yaml_path.exists():
            self.warnings.append(f"{filename} not found, using defaults")
            return {}

        try:
            with open(yaml_path, 'r') as f:
                return yaml.safe_load(f) or {}
        except Exception as e:
            self.errors.append(f"Failed to load {filename}: {e}")
            return {}

    def write_file(self, path, content, executable=False):
        """Write content to file with proper permissions"""
        try:
            path = Path(path)
            path.parent.mkdir(parents=True, exist_ok=True)

            with open(path, 'w', encoding='utf-8') as f:
                f.write(content)

            if executable:
                st = os.stat(path)
                os.chmod(path, st.st_mode | stat.S_IEXEC)

            self.fixes_applied.append(f"Wrote: {path}")
            return True
        except Exception as e:
            self.errors.append(f"Failed to write {path}: {e}")
            return False

    def get_build_script(self):
        """Generate build2.sh with proper escaping and logic"""
        meta = self.genome.get('meta', {})
        os_name = meta.get('frameworkname', 'FurryOS').title().replace(' ', '')
        version = meta.get('version', '8.1.0')
        codename = self.genome.get('liveenvironment', {}).get('bootloader', {}).get('class', 'trixie')
        if codename == 'x86_64':
            codename = 'trixie'

        return f"""#!/bin/bash
# FurryOS Build System v{version}
# Generated by Universal Patcher on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

set -e  # Exit on error
set -o pipefail  # Catch pipe errors

# ============================================================================
# CONFIGURATION
# ============================================================================

OS_NAME="{os_name}"
CODENAME="{codename}"
ARCH="amd64"
DATE=$(date +%Y%m%d)
BUILD_LOG="build-${{DATE}}.log"

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'  # No Color

# ============================================================================
# FUNCTIONS
# ============================================================================

log_info() {{
    echo -e "${{BLUE}}[INFO]${{NC}} $1" | tee -a "$BUILD_LOG"
}}

log_success() {{
    echo -e "${{GREEN}}[SUCCESS]${{NC}} $1" | tee -a "$BUILD_LOG"
}}

log_error() {{
    echo -e "${{RED}}[ERROR]${{NC}} $1" | tee -a "$BUILD_LOG"
}}

check_root() {{
    if [ "$EUID" -ne 0 ]; then
        log_error "This script must be run as root (use sudo)"
        exit 1
    fi
}}

check_dependencies() {{
    log_info "Checking dependencies..."

    local missing_deps=()

    for cmd in lb rsync debootstrap; do
        if ! command -v "$cmd" &> /dev/null; then
            missing_deps+=("$cmd")
        fi
    done

    if [ ${{#missing_deps[@]}} -gt 0 ]; then
        log_error "Missing dependencies: ${{missing_deps[*]}}"
        log_info "Install with: sudo apt install live-build rsync debootstrap"
        exit 1
    fi
}}

# ============================================================================
# MAIN BUILD PROCESS
# ============================================================================

log_info "============================================"
log_info "${{OS_NAME}} Build System v{version}"
log_info "============================================"

# 1. Root check
check_root

# 2. Dependency check
check_dependencies

# 3. Clean previous build
log_info "Cleaning previous build artifacts..."
lb clean --purge 2>&1 | tee -a "$BUILD_LOG"
rm -f *.iso

# 4. Configure live-build
log_info "Configuring live-build for Debian ${{CODENAME}}..."

lb config \
    --distribution "$CODENAME" \
    --architecture "$ARCH" \
    --archive-areas "main contrib non-free non-free-firmware" \
    --security true \
    --updates true \
    --backports false \
    --bootappend-live "boot=live components quiet splash hostname=furryos" \
    --linux-packages "linux-image linux-headers" \
    --iso-volume "${{OS_NAME}}_Live_${{DATE}}" \
    --iso-application "${{OS_NAME}}" \
    --iso-publisher "Anthro Entertainment LLC" \
    --memtest none \
    2>&1 | tee -a "$BUILD_LOG"

# 5. Inject assets and configurations
log_info "Injecting assets and configurations..."

# Create directory structure
mkdir -p config/includes.chroot/usr/share/backgrounds/furryos
mkdir -p config/includes.chroot/usr/share/icons/furryos
mkdir -p config/includes.chroot/etc/skel/Desktop
mkdir -p config/includes.chroot/usr/local/bin
mkdir -p config/hooks/live

# Copy wallpapers
if [ -d "assets/wallpapers" ]; then
    log_info "Copying wallpapers..."
    rsync -a assets/wallpapers/ config/includes.chroot/usr/share/backgrounds/furryos/
fi

# Copy icons
if [ -d "assets/icons" ]; then
    log_info "Copying icons..."
    rsync -a assets/icons/ config/includes.chroot/usr/share/icons/furryos/
fi

# Set executable permissions on custom scripts
if [ -f "config/includes.chroot/usr/local/bin/furry-admin" ]; then
    chmod +x config/includes.chroot/usr/local/bin/furry-admin
fi

# Set executable permissions on hooks
chmod +x config/hooks/live/*.hook.chroot 2>/dev/null || true

# 6. Build ISO
log_info "Building ISO (this will take a while)..."
if lb build 2>&1 | tee -a "$BUILD_LOG"; then
    log_success "ISO build completed successfully!"
else
    log_error "ISO build failed! Check $BUILD_LOG for details."
    exit 1
fi

# 7. Finalize and rename ISO
ISO_FILENAME="${{OS_NAME}}_v{version}_${{DATE}}.iso"

if [ -f "live-image-${{ARCH}}.hybrid.iso" ]; then
    mv "live-image-${{ARCH}}.hybrid.iso" "$ISO_FILENAME"

    # Fix ownership (give back to the user who ran sudo)
    if [ -n "$SUDO_USER" ]; then
        chown "$SUDO_USER:$SUDO_USER" "$ISO_FILENAME"
    fi

    # Calculate SHA256 checksum
    sha256sum "$ISO_FILENAME" > "${{ISO_FILENAME}}.sha256"
    if [ -n "$SUDO_USER" ]; then
        chown "$SUDO_USER:$SUDO_USER" "${{ISO_FILENAME}}.sha256"
    fi

    log_success "============================================"
    log_success "BUILD SUCCESSFUL!"
    log_success "============================================"
    log_success "ISO: $ISO_FILENAME"
    log_success "Size: $(du -h "$ISO_FILENAME" | cut -f1)"
    log_success "SHA256: $(cat "${{ISO_FILENAME}}.sha256" | cut -d' ' -f1)"
    log_success "Log: $BUILD_LOG"
else
    log_error "Build failed - no ISO file generated!"
    log_error "Check $BUILD_LOG for details"
    exit 1
fi
"""

    def get_package_list(self):
        """Generate desktop.list.chroot from GENOME.yaml"""
        installer = self.genome.get('installer', {})
        packages_config = installer.get('step4packages', {})

        # Base system packages
        packages = [
            "# Base System",
            "task-mate-desktop",
            "mate-utils",
            "mate-tweak",
            "network-manager-gnome",
            "",
            "# Firmware",
            "firmware-linux",
            "firmware-iwlwifi", 
            "firmware-misc-nonfree",
            "",
            "# Filesystem Tools",
            "btrfs-progs",
            "cryptsetup",
            "dosfstools",
            "gparted",
            "timeshift",
            "",
            "# Boot & EFI",
            "grub-efi-amd64-signed",
            "shim-signed",
            "",
            "# Modern App Ecosystem",
            "flatpak",
            "gnome-software-plugin-flatpak",
            "podman",
            "distrobox",
            "",
            "# Core Utilities",
            "htop",
            "curl",
            "git",
            "vim",
            "wget",
            "neovim",
            "",
            "# Installer",
            "calamares",
            "calamares-settings-debian",
            "",
            "# Boot Animation",
            "plymouth",
            "plymouth-themes",
            "",
            "# Admin Panel Dependencies",
            "zenity",
            "python3-tk",
            "",
            "# Multimedia",
            "vlc",
            "mpv",
        ]

        # Add bundle packages based on user config
        bundles = self.user_config.get('softwarebundles', {})

        if bundles.get('gaming', False):
            packages.extend([
                "",
                "# Gaming (installed via hook to avoid conflicts)",
                "# steam-installer",
            ])

        if bundles.get('devtools', False):
            packages.extend([
                "",
                "# Development Tools",
                "build-essential",
                "python3-pip",
                "nodejs",
            ])

        if bundles.get('office', False):
            packages.extend([
                "",
                "# Office Suite",
                "libreoffice",
                "thunderbird",
            ])

        return "\n".join(packages)

    def get_steam_hook(self):
        """Generate Steam installation hook"""
        return """#!/bin/sh
# 99-install-steam.hook.chroot
# Installs Steam with proper 32-bit architecture support

echo "FurryOS: Setting up Gaming Mode..."

# Enable 32-bit architecture (required for Steam)
dpkg --add-architecture i386
apt-get update

# Install Steam and 32-bit graphics drivers
apt-get install -y \
    steam-installer \
    mesa-vulkan-drivers:i386 \
    libglx-mesa0:i386 \
    libgl1-mesa-dri:i386

echo "Steam installed successfully!"
"""

    def get_appearance_hook(self):
        """Generate appearance/branding hook"""
        meta = self.genome.get('meta', {})
        os_name = meta.get('frameworkname', 'FurryOS').title()

        return f"""#!/bin/sh
# 05-furryos-appearance.hook.chroot
# Applies FurryOS branding and theming

echo "Applying {os_name} branding and theme..."

# Update OS release information
sed -i 's/PRETTY_NAME=.*/PRETTY_NAME="{os_name}"/' /etc/os-release
sed -i 's/NAME="Debian GNU\\/Linux"/NAME="{os_name}"/' /etc/os-release

# Configure MATE desktop settings
mkdir -p /usr/share/glib-2.0/schemas

cat > /usr/share/glib-2.0/schemas/99-furryos.gschema.override << 'EOF'
[org.mate.background]
picture-filename='/usr/share/backgrounds/furryos/wallpaper.png'
primary-color='#000000'
secondary-color='#000000'

[org.mate.interface]
gtk-theme='Menta'
icon-theme='mate'
font-name='Sans 10'
color-scheme='prefer-dark'

[org.mate.panel]
default-layout='redmond'

[org.mate.Marco.general]
theme='Menta'
EOF

# Compile schemas
glib-compile-schemas /usr/share/glib-2.0/schemas

echo "{os_name} appearance applied successfully!"
"""

    def get_zram_hook(self):
        """Generate ZRAM setup hook"""
        system_opts = self.user_config.get('systemoptimizations', {})
        if not system_opts.get('zramenabled', True):
            return None

        zram_ratio = system_opts.get('zramratio', 0.5)

        return f"""#!/bin/sh
# 01-setup-zram.hook.chroot
# Configures ZRAM for improved memory management

echo "Setting up ZRAM..."

# Install zram-tools
apt-get install -y zram-tools

# Configure ZRAM
cat > /etc/default/zramswap << EOF
# ZRAM configuration for FurryOS
ALGO=zstd
PERCENT={int(zram_ratio * 100)}
PRIORITY=100
EOF

echo "ZRAM configured successfully!"
"""

    def get_admin_panel_script(self):
        """Generate furry-admin GUI panel"""
        return """#!/usr/bin/env python3
# FurryOS Admin Control Panel

import tkinter as tk
from tkinter import messagebox
import subprocess
import os

def run_command(cmd):
    try:
        subprocess.run(cmd, shell=True, check=True)
        messagebox.showinfo("Success", "Operation completed successfully!")
    except Exception as e:
        messagebox.showerror("Error", f"Operation failed: {e}")

def set_profile(profile):
    if profile == "gamer":
        cmd = "sudo systemctl stop cups bluetooth; echo 'Gamer Mode Active'"
    elif profile == "paranoid":
        cmd = "sudo ufw enable; sudo ufw default deny incoming; echo 'Paranoid Mode Active'"
    elif profile == "granny":
        cmd = "gsettings set org.mate.interface document-font-name 'Sans 14'; echo 'Granny Mode Active'"
    elif profile == "hacker":
        cmd = "x-terminal-emulator &"
    else:
        return

    run_command(cmd)

def launch_snapshot():
    run_command("sudo timeshift-gtk")

# Create main window
root = tk.Tk()
root.title("FurryOS Control Center")
root.geometry("500x550")
root.configure(bg="#222")

# Header
tk.Label(
    root, 
    text="FurryOS Control Center",
    bg="#222",
    fg="#FF6600",
    font=("Arial", 20, "bold")
).pack(pady=20)

# Profile selection
tk.Label(
    root,
    text="Select System Profile",
    bg="#222",
    fg="#AAA",
    font=("Arial", 12)
).pack(pady=10)

# Profile buttons
btn_frame = tk.Frame(root, bg="#222")
btn_frame.pack(pady=10)

def make_button(text, profile, color):
    tk.Button(
        btn_frame,
        text=text,
        command=lambda: set_profile(profile),
        width=30,
        height=2,
        bg=color,
        fg="white",
        font=("Arial", 11, "bold"),
        relief="flat"
    ).pack(pady=5)

make_button("🎮 Gamer Mode", "gamer", "#D32F2F")
make_button("👵 Granny Mode", "granny", "#1976D2")
make_button("💻 Hacker Mode", "hacker", "#388E3C")
make_button("🔒 Paranoid Mode", "paranoid", "#424242")

# System maintenance
tk.Label(
    root,
    text="System Maintenance",
    bg="#222",
    fg="#AAA",
    font=("Arial", 12)
).pack(pady=15)

tk.Button(
    root,
    text="📸 System Snapshot & Rollback",
    command=launch_snapshot,
    width=30,
    height=2,
    bg="#FF9800",
    fg="black",
    font=("Arial", 11, "bold")
).pack(pady=5)

# Exit button
tk.Button(
    root,
    text="EXIT",
    command=root.quit,
    bg="black",
    fg="white",
    relief="flat",
    font=("Arial", 10)
).pack(pady=20)

root.mainloop()
"""

    def get_admin_setup_hook(self):
        """Hook to ensure admin panel is executable"""
        return """#!/bin/sh
# 06-setup-admin.hook.chroot
# Ensures the admin panel is executable

chmod +x /usr/local/bin/furry-admin
"""

    def remove_fastfetch(self):
        """Remove fastfetch from all package lists"""
        log_msg = "Removing fastfetch references..."
        print(log_msg)

        removed_count = 0

        # Walk through config directory
        for root, dirs, files in os.walk(self.config_dir):
            for file in files:
                if file.endswith('.list.chroot') or file.endswith('.list'):
                    filepath = Path(root) / file
                    try:
                        with open(filepath, 'r', encoding='utf-8') as f:
                            lines = f.readlines()

                        # Filter out fastfetch and neofetch
                        new_lines = [line for line in lines if 'fastfetch' not in line.lower() and 'neofetch' not in line.lower()]

                        if len(lines) != len(new_lines):
                            with open(filepath, 'w', encoding='utf-8') as f:
                                f.writelines(new_lines)
                            removed_count += 1
                            self.fixes_applied.append(f"Removed fastfetch from {filepath.name}")
                    except Exception as e:
                        self.warnings.append(f"Could not process {filepath}: {e}")

        if removed_count == 0:
            self.fixes_applied.append("No fastfetch references found (clean)")

        return removed_count

    def patch_all(self):
        """Main patching routine"""
        print("=" * 60)
        print("FurryOS Universal Patcher v8.1.0")
        print("=" * 60)
        print()

        # 1. Clean fastfetch issues
        print("[1/7] Cleaning fastfetch references...")
        self.remove_fastfetch()

        # 2. Write build script
        print("[2/7] Generating build2.sh...")
        self.write_file(
            self.root / "build2.sh",
            self.get_build_script(),
            executable=True
        )

        # 3. Write package list
        print("[3/7] Generating package lists...")
        self.write_file(
            self.config_dir / "package-lists" / "desktop.list.chroot",
            self.get_package_list()
        )

        # 4. Write hooks
        print("[4/7] Generating hook scripts...")
        hooks_dir = self.config_dir / "hooks" / "live"

        # Appearance hook
        self.write_file(
            hooks_dir / "05-furryos-appearance.hook.chroot",
            self.get_appearance_hook(),
            executable=True
        )

        # Steam hook (if gaming enabled)
        bundles = self.user_config.get('softwarebundles', {})
        if bundles.get('gaming', False):
            self.write_file(
                hooks_dir / "99-install-steam.hook.chroot",
                self.get_steam_hook(),
                executable=True
            )

        # ZRAM hook (if enabled)
        zram_hook = self.get_zram_hook()
        if zram_hook:
            self.write_file(
                hooks_dir / "01-setup-zram.hook.chroot",
                zram_hook,
                executable=True
            )

        # Admin setup hook
        self.write_file(
            hooks_dir / "06-setup-admin.hook.chroot",
            self.get_admin_setup_hook(),
            executable=True
        )

        # 5. Write admin panel
        print("[5/7] Generating admin panel...")
        self.write_file(
            self.config_dir / "includes.chroot" / "usr" / "local" / "bin" / "furry-admin",
            self.get_admin_panel_script(),
            executable=True
        )

        # 6. Create desktop shortcut
        print("[6/7] Creating desktop shortcut...")
        desktop_entry = """[Desktop Entry]
Type=Application
Name=FurryOS Control Center
Comment=Manage FurryOS system profiles
Exec=furry-admin
Icon=utilities-system-monitor
Terminal=false
Categories=System;Settings;
"""
        self.write_file(
            self.config_dir / "includes.chroot" / "usr" / "share" / "applications" / "furry-admin.desktop",
            desktop_entry
        )

        # 7. Generate report
        print("[7/7] Generating patch report...")
        self.generate_report()

        print()
        print("=" * 60)
        print("PATCHING COMPLETE!")
        print("=" * 60)
        print()
        print("Next steps:")
        print("  1. Review any warnings above")
        print("  2. Run: sudo ./build2.sh")
        print("  3. Wait for ISO to build")
        print()

        return len(self.errors) == 0

    def generate_report(self):
        """Generate detailed patch report"""
        report_path = self.root / "PATCH_REPORT.txt"

        with open(report_path, 'w', encoding='utf-8') as f:
            f.write("FurryOS Universal Patcher Report\n")
            f.write(f"Generated: {datetime.now()}\n")
            f.write("=" * 60 + "\n\n")

            f.write(f"Fixes Applied: {len(self.fixes_applied)}\n")
            for fix in self.fixes_applied:
                f.write(f"  ✓ {fix}\n")
            f.write("\n")

            if self.warnings:
                f.write(f"Warnings: {len(self.warnings)}\n")
                for warning in self.warnings:
                    f.write(f"  ⚠ {warning}\n")
                f.write("\n")

            if self.errors:
                f.write(f"Errors: {len(self.errors)}\n")
                for error in self.errors:
                    f.write(f"  ✗ {error}\n")
                f.write("\n")

            f.write("Configuration Summary:\n")
            f.write(f"  OS Name: {self.genome.get('meta', {}).get('frameworkname', 'FurryOS')}\n")
            f.write(f"  Version: {self.genome.get('meta', {}).get('version', '8.1.0')}\n")
            f.write(f"  User Profile: {self.user_config.get('userprofile', {}).get('username', 'anthrouser')}\n")
            f.write(f"  Gaming Bundle: {self.user_config.get('softwarebundles', {}).get('gaming', False)}\n")
            f.write(f"  ZRAM Enabled: {self.user_config.get('systemoptimizations', {}).get('zramenabled', True)}\n")

        self.fixes_applied.append(f"Generated report: {report_path}")
        print(f"\n📄 Detailed report saved to: {report_path}")


if __name__ == "__main__":
    patcher = FurryOSPatcher()
    success = patcher.patch_all()
    sys.exit(0 if success else 1)
